name: Continuous Integration

# Trigger the workflow on any push to the repository
on:
  push:
    branches:
      - main    # Change this to your primary branch name (e.g., 'master' or 'main')

# Define the jobs for the workflow
jobs:
  test:
    runs-on: ubuntu-latest  # Choose the runner (Ubuntu in this case)
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3  # Checkout the code from the repository

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'   # Define the Python version you want to use

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install dependencies for your project

      - name: Run Tests
        run: |
          pytest  # Run your tests using pytest (or another testing framework you prefer)
          
      - name: Upload Test Results
        if: failure()  # This step uploads test results only if tests fail
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results/  # Path to your test results, adjust as needed

      - name: Send Notifications on Failure (Optional)
        if: failure()
        run: |
          echo "Tests failed! Please review the test results and fix the issues."
